export const COMPANY_REQUEST = 'COMPANY_REQUEST';
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS';

export const SAVE_COMPANY_REQUEST = 'SAVE_COMPANY_REQUEST';
export const SAVE_COMPANY_SUCCESS = 'SAVE_COMPANY_SUCCESS';
