export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';

export const ADD_MOD_ROLE_REQUEST = 'ADD_MOD_ROLE_REQUEST';
export const ADD_MOD_ROLE_SUCCESS = 'ADD_MOD_ROLE_SUCCESS';

export const REMOVE_MOD_ROLE_REQUEST = 'REMOVE_MOD_ROLE_REQUEST';
export const REMOVE_MOD_ROLE_SUCCESS = 'REMOVE_MOD_ROLE_SUCCESS';
